sudo: false
language: java
env:
  - GRADLE_USER_HOME=gradle-cache
cache:
  directories:
    - gradle-cache
jdk:
  - oraclejdk8
before_install:
  - wget http://services.gradle.org/distributions/gradle-2.13-bin.zip
  - unzip gradle-2.13-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.13
  - export PATH=$GRADLE_HOME/bin:$PATH
