sudo: required
dist: trusty
language: java
os:
- linux
notifications:
  email: true
jdk:
  - oraclejdk7
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y wget unzip build-essential
script:
- ./make.sh travis
env:
  global:
  - BINTRAY_USER: riccardo
  - secure: "NOPE"